import assert from "node:assert/strict";
import test from "node:test";
import {
	getCatalogModels,
	getProviderAdapterFamily,
	getProviderDefinition,
	getProviderDefaultEndpointType,
	getProviderDefaultModel,
	getProviderEndpointTypeForModel,
	getProviderFallbackModels,
	getProviderIds,
	isProviderId
} from "../../../src/providers/provider-registry.js";
import { listProviderModels } from "../../../src/providers/provider-models.js";

test("provider catalog exposes valid built-in providers and model references", (): void => {
	const providerIds: string[] = getProviderIds();
	assert.deepEqual(providerIds, ["deepseek", "moonshot", "openai", "zhipu", "dashscope", "volcengine", "minimax", "stepfun", "iflytek", "opencode", "opencode_go", "qianfan"]);
	assert.equal(isProviderId("deepseek"), true);
	assert.equal(isProviderId("unknown"), false);

	for (const provider of providerIds) {
		const defaultModel: string = getProviderDefaultModel(provider);
		const fallbackModels = getProviderFallbackModels(provider);
		assert.ok(fallbackModels.some((model) => model.id === defaultModel));
		for (const model of fallbackModels) {
			assert.equal(model.provider, provider);
			assert.ok(model.contextWindowTokens > 0);
			assert.ok(model.maxOutputTokens > 0);
		}
	}

	assert.equal(getProviderDefaultEndpointType("deepseek"), "openai-chat-completions");
	assert.equal(getProviderAdapterFamily("deepseek"), "openai-compatible");
	assert.equal(getProviderDefaultEndpointType("openai"), "openai-responses");
	assert.equal(getProviderAdapterFamily("openai"), "openai-responses");
	assert.equal(getProviderDefinition("openai").modelListMode, "catalog-recommended");
	assert.equal(getProviderDefaultModel("moonshot"), "kimi-k3");
	assert.equal(getProviderDefaultEndpointType("moonshot"), "openai-chat-completions");
	assert.equal(getProviderAdapterFamily("moonshot"), "openai-compatible");
	const moonshotModels = getProviderFallbackModels("moonshot");
	assert.equal(moonshotModels.find((model) => model.id === "kimi-k3")?.contextWindowTokens, 1_048_576);
	assert.equal(moonshotModels.find((model) => model.id === "kimi-k3")?.maxOutputTokens, 131_072);
	assert.equal(moonshotModels.find((model) => model.id === "kimi-k3")?.capabilities.imageInput, true);
	assert.equal(moonshotModels.find((model) => model.id === "kimi-k3")?.capabilities.reasoning, true);
	assert.equal(moonshotModels.find((model) => model.id === "kimi-k3")?.capabilities.tools, true);
	assert.equal(moonshotModels.find((model) => model.id === "kimi-k3")?.capabilities.vision, true);
	assert.equal(getProviderDefaultModel("zhipu"), "glm-5.2");
	assert.equal(getProviderDefaultEndpointType("zhipu"), "openai-chat-completions");
	assert.equal(getProviderAdapterFamily("zhipu"), "openai-compatible");
	const zhipuModels = getProviderFallbackModels("zhipu");
	assert.equal(zhipuModels.find((model) => model.id === "glm-5v-turbo")?.capabilities.imageInput, true);
	assert.equal(zhipuModels.find((model) => model.id === "glm-5v-turbo")?.capabilities.vision, true);
	assert.equal(zhipuModels.find((model) => model.id === "glm-5.2")?.capabilities.reasoning, true);
	assert.equal(zhipuModels.find((model) => model.id === "glm-5.2")?.capabilities.tools, true);
	assert.equal(zhipuModels.find((model) => model.id === "glm-5.2")?.capabilities.webSearch, true);
	assert.equal(zhipuModels.find((model) => model.id === "glm-5.2")?.contextWindowTokens, 1_000_000);
	assert.equal(getProviderDefaultModel("dashscope"), "qwen3.7-plus");
	assert.equal(getProviderDefinition("dashscope").modelListMode, "catalog-recommended");
	assert.equal(getProviderDefaultEndpointType("dashscope"), "openai-chat-completions");
	assert.equal(getProviderAdapterFamily("dashscope"), "openai-compatible");
	const dashscopeModels = getProviderFallbackModels("dashscope");
	assert.equal(dashscopeModels.find((model) => model.id === "qwen3.7-plus")?.capabilities.reasoning, true);
	assert.equal(dashscopeModels.find((model) => model.id === "qwen3.7-plus")?.capabilities.tools, true);
	assert.equal(dashscopeModels.find((model) => model.id === "qwen-image-2.0-pro")?.capabilities.imageGeneration, true);
	assert.equal(dashscopeModels.find((model) => model.id === "qwen-image-2.0-pro")?.capabilities.imageEdit, true);
	assert.equal(dashscopeModels.find((model) => model.id === "qwen-image-2.0-pro-2026-06-22")?.capabilities.imageGeneration, true);
	assert.equal(dashscopeModels.find((model) => model.id === "qwen-image-max")?.capabilities.imageGeneration, true);
	assert.equal(dashscopeModels.find((model) => model.id === "qwen-image-max")?.capabilities.imageEdit, undefined);
	assert.equal(dashscopeModels.find((model) => model.id === "qwen-image-edit")?.capabilities.imageGeneration, undefined);
	assert.equal(dashscopeModels.find((model) => model.id === "qwen-image-edit")?.capabilities.imageEdit, true);
	assert.equal(dashscopeModels.find((model) => model.id === "qwen-image-edit-plus-2025-12-15")?.capabilities.imageEdit, true);
	assert.equal(getProviderDefaultModel("volcengine"), "doubao-seed-evolving");
	assert.equal(getProviderDefinition("volcengine").modelListMode, "catalog-recommended");
	assert.equal(getProviderDefaultEndpointType("volcengine"), "openai-chat-completions");
	assert.equal(getProviderAdapterFamily("volcengine"), "openai-compatible");
	const volcengineModels = getProviderFallbackModels("volcengine");
	assert.equal(volcengineModels.length, 3);
	assert.equal(volcengineModels.find((model) => model.id === "doubao-seed-evolving")?.capabilities.imageInput, true);
	assert.equal(volcengineModels.find((model) => model.id === "doubao-seed-evolving")?.capabilities.videoInput, true);
	assert.equal(volcengineModels.find((model) => model.id === "doubao-seed-evolving")?.capabilities.reasoning, true);
	assert.equal(volcengineModels.find((model) => model.id === "doubao-seed-evolving")?.capabilities.tools, true);
	assert.equal(volcengineModels.find((model) => model.id === "doubao-seed-evolving")?.capabilities.vision, true);
	assert.equal(volcengineModels.find((model) => model.id === "doubao-seed-2-1-pro-260628")?.capabilities.imageInput, true);
	assert.equal(volcengineModels.find((model) => model.id === "doubao-seed-2-1-pro-260628")?.capabilities.tools, true);
	assert.equal(volcengineModels.find((model) => model.id === "doubao-seedream-5-0-pro-260628")?.capabilities.imageGeneration, true);
	assert.equal(volcengineModels.find((model) => model.id === "doubao-seedream-5-0-pro-260628")?.capabilities.imageEdit, undefined);
	assert.equal(getProviderDefaultModel("minimax"), "MiniMax-M3");
	assert.equal(getProviderDefinition("minimax").modelListMode, "catalog-recommended");
	assert.equal(getProviderDefaultEndpointType("minimax"), "openai-chat-completions");
	assert.equal(getProviderAdapterFamily("minimax"), "openai-compatible");
	assert.equal(getProviderDefinition("minimax").defaultBaseUrl, "https://api.minimaxi.com/v1");
	assert.equal(getProviderDefinition("minimax").modelsPath, "/models");
	const minimaxModels = getProviderFallbackModels("minimax");
	assert.equal(minimaxModels.length, 10);
	assert.equal(minimaxModels.find((model) => model.id === "MiniMax-M3")?.contextWindowTokens, 1_000_000);
	assert.equal(minimaxModels.find((model) => model.id === "MiniMax-M3")?.capabilities.imageInput, true);
	assert.equal(minimaxModels.find((model) => model.id === "MiniMax-M3")?.capabilities.videoInput, true);
	assert.equal(minimaxModels.find((model) => model.id === "MiniMax-M3")?.capabilities.reasoning, true);
	assert.equal(minimaxModels.find((model) => model.id === "MiniMax-M3")?.capabilities.tools, true);
	assert.equal(minimaxModels.find((model) => model.id === "MiniMax-M3")?.capabilities.vision, true);
	assert.equal(minimaxModels.find((model) => model.id === "MiniMax-M2.7")?.capabilities.tools, true);
	assert.equal(minimaxModels.find((model) => model.id === "image-01")?.capabilities.imageGeneration, true);
	assert.equal(minimaxModels.find((model) => model.id === "image-01")?.capabilities.imageEdit, undefined);
	assert.equal(minimaxModels.find((model) => model.id === "image-01-live")?.capabilities.imageGeneration, true);
	assert.equal(minimaxModels.find((model) => model.id === "image-01-live")?.capabilities.imageEdit, undefined);
	assert.equal(getProviderDefaultModel("stepfun"), "step-3.7-flash");
	assert.equal(getProviderDefinition("stepfun").modelListMode, "catalog-recommended");
	assert.equal(getProviderDefaultEndpointType("stepfun"), "openai-chat-completions");
	assert.equal(getProviderAdapterFamily("stepfun"), "openai-compatible");
	assert.equal(getProviderDefinition("stepfun").defaultBaseUrl, "https://api.stepfun.com/v1");
	assert.equal(getProviderDefinition("stepfun").modelsPath, "/models");
	const stepfunModels = getProviderFallbackModels("stepfun");
	assert.equal(stepfunModels.length, 3);
	assert.equal(stepfunModels.find((model) => model.id === "step-3.7-flash")?.contextWindowTokens, 256_000);
	assert.equal(stepfunModels.find((model) => model.id === "step-3.7-flash")?.capabilities.imageInput, true);
	assert.equal(stepfunModels.find((model) => model.id === "step-3.7-flash")?.capabilities.reasoning, true);
	assert.equal(stepfunModels.find((model) => model.id === "step-3.7-flash")?.capabilities.tools, true);
	assert.equal(stepfunModels.find((model) => model.id === "step-3.7-flash")?.capabilities.vision, true);
	assert.equal(stepfunModels.find((model) => model.id === "step-3.5-flash")?.capabilities.reasoning, true);
	assert.equal(stepfunModels.find((model) => model.id === "step-3.5-flash")?.capabilities.tools, true);
	assert.equal(stepfunModels.find((model) => model.id === "step-3.5-flash-2603")?.capabilities.reasoning, true);
	assert.equal(stepfunModels.find((model) => model.id === "step-3.5-flash-2603")?.capabilities.tools, true);
	assert.equal(getProviderDefaultModel("iflytek"), "4.0Ultra");
	assert.equal(getProviderDefinition("iflytek").modelListMode, "catalog-only");
	assert.equal(getProviderDefaultEndpointType("iflytek"), "openai-chat-completions");
	assert.equal(getProviderAdapterFamily("iflytek"), "openai-compatible");
	assert.equal(getProviderDefinition("iflytek").defaultBaseUrl, "https://spark-api-open.xf-yun.com/v1");
	assert.equal(getProviderDefinition("iflytek").modelsPath, "/models");
	assert.equal(getProviderDefinition("iflytek").endpointConfigs["openai-chat-completions"]?.toolCallsSwitch, true);
	const iflytekModels = getProviderFallbackModels("iflytek");
	assert.equal(iflytekModels.length, 4);
	assert.equal(iflytekModels.find((model) => model.id === "4.0Ultra")?.contextWindowTokens, 32_768);
	assert.equal(iflytekModels.find((model) => model.id === "4.0Ultra")?.maxOutputTokens, 32_768);
	assert.equal(iflytekModels.find((model) => model.id === "4.0Ultra")?.capabilities.tools, true);
	assert.equal(iflytekModels.find((model) => model.id === "pro-128k")?.contextWindowTokens, 131_072);
	assert.equal(iflytekModels.find((model) => model.id === "pro-128k")?.capabilities.tools, undefined);
	assert.equal(iflytekModels.find((model) => model.id === "generalv3")?.contextWindowTokens, 8_192);
	assert.equal(iflytekModels.find((model) => model.id === "lite")?.maxOutputTokens, 4_096);
	assert.equal(getProviderDefaultModel("opencode"), "kimi-k2.7-code");
	assert.equal(getProviderDefinition("opencode").modelListMode, "catalog-recommended");
	assert.equal(getProviderDefaultEndpointType("opencode"), "openai-chat-completions");
	assert.equal(getProviderAdapterFamily("opencode"), "openai-compatible");
	assert.equal(getProviderDefinition("opencode").defaultBaseUrl, "https://opencode.ai/zen/v1");
	assert.equal(getProviderDefinition("opencode").modelsPath, "/models");
	const opencodeModels = getProviderFallbackModels("opencode");
	assert.equal(opencodeModels.length, 6);
	assert.equal(opencodeModels.find((model) => model.id === "kimi-k2.7-code")?.contextWindowTokens, 256_000);
	assert.equal(opencodeModels.find((model) => model.id === "kimi-k2.7-code")?.capabilities.reasoning, true);
	assert.equal(opencodeModels.find((model) => model.id === "kimi-k2.7-code")?.capabilities.tools, true);
	assert.equal(opencodeModels.find((model) => model.id === "deepseek-v4-pro")?.maxOutputTokens, 384_000);
	assert.equal(opencodeModels.find((model) => model.id === "deepseek-v4-flash")?.contextWindowTokens, 1_000_000);
	assert.equal(opencodeModels.find((model) => model.id === "glm-5.2")?.maxOutputTokens, 128_000);
	assert.equal(opencodeModels.find((model) => model.id === "minimax-m3")?.maxOutputTokens, 131_072);
	assert.equal(opencodeModels.find((model) => model.id === "grok-4.5")?.contextWindowTokens, 256_000);
	assert.equal(getProviderDefaultModel("opencode_go"), "kimi-k3");
	assert.equal(getProviderDefinition("opencode_go").modelListMode, "catalog-recommended");
	assert.equal(getProviderDefaultEndpointType("opencode_go"), "openai-chat-completions");
	assert.equal(getProviderAdapterFamily("opencode_go"), "openai-compatible");
	assert.equal(getProviderAdapterFamily("opencode_go", "anthropic-messages"), "anthropic-compatible");
	assert.equal(getProviderDefinition("opencode_go").defaultBaseUrl, "https://opencode.ai/zen/go/v1");
	assert.equal(getProviderDefinition("opencode_go").modelsPath, "/models");
	assert.equal(getProviderEndpointTypeForModel("opencode_go", "kimi-k3"), "openai-chat-completions");
	assert.equal(getProviderEndpointTypeForModel("opencode_go", "minimax-m3"), "anthropic-messages");
	const opencodeGoModels = getProviderFallbackModels("opencode_go");
	assert.equal(opencodeGoModels.length, 16);
	assert.equal(opencodeGoModels.find((model) => model.id === "kimi-k3")?.contextWindowTokens, 1_048_576);
	assert.equal(opencodeGoModels.find((model) => model.id === "kimi-k3")?.maxOutputTokens, 131_072);
	assert.equal(opencodeGoModels.find((model) => model.id === "kimi-k3")?.capabilities.imageInput, true);
	assert.equal(opencodeGoModels.find((model) => model.id === "kimi-k3")?.capabilities.tools, true);
	assert.equal(opencodeGoModels.find((model) => model.id === "kimi-k3")?.capabilities.vision, true);
	assert.equal(opencodeGoModels.find((model) => model.id === "kimi-k2.6")?.capabilities.imageInput, true);
	assert.equal(opencodeGoModels.find((model) => model.id === "deepseek-v4-pro")?.maxOutputTokens, 384_000);
	assert.equal(opencodeGoModels.find((model) => model.id === "glm-5.2")?.contextWindowTokens, 1_000_000);
	assert.equal(opencodeGoModels.find((model) => model.id === "grok-4.5")?.contextWindowTokens, 256_000);
	assert.equal(opencodeGoModels.find((model) => model.id === "mimo-v2.5-pro")?.capabilities.reasoning, true);
	assert.equal(opencodeGoModels.find((model) => model.id === "minimax-m3")?.endpointType, "anthropic-messages");
	assert.equal(opencodeGoModels.find((model) => model.id === "minimax-m3")?.capabilities.vision, true);
	assert.equal(opencodeGoModels.find((model) => model.id === "qwen3.7-plus")?.endpointType, "anthropic-messages");
	assert.equal(getProviderDefaultModel("qianfan"), "ernie-5.1");
	assert.equal(getProviderDefinition("qianfan").modelListMode, "catalog-recommended");
	assert.equal(getProviderDefaultEndpointType("qianfan"), "openai-chat-completions");
	assert.equal(getProviderAdapterFamily("qianfan"), "openai-compatible");
	assert.equal(getProviderDefinition("qianfan").defaultBaseUrl, "https://qianfan.baidubce.com/v2");
	assert.equal(getProviderDefinition("qianfan").modelsPath, "/models");
	const qianfanModels = getProviderFallbackModels("qianfan");
	assert.equal(qianfanModels.length, 7);
	assert.equal(qianfanModels.find((model) => model.id === "ernie-5.1")?.contextWindowTokens, 131_072);
	assert.equal(qianfanModels.find((model) => model.id === "ernie-5.1")?.maxOutputTokens, 65_536);
	assert.equal(qianfanModels.find((model) => model.id === "ernie-5.1")?.capabilities.reasoning, true);
	assert.equal(qianfanModels.find((model) => model.id === "ernie-5.1")?.capabilities.tools, true);
	assert.equal(qianfanModels.find((model) => model.id === "ernie-5.0")?.capabilities.imageInput, true);
	assert.equal(qianfanModels.find((model) => model.id === "ernie-5.0")?.capabilities.vision, true);
	assert.equal(qianfanModels.find((model) => model.id === "ernie-5.0-thinking-latest")?.capabilities.reasoning, true);
	assert.equal(qianfanModels.find((model) => model.id === "ernie-x1.1")?.contextWindowTokens, 65_536);
	assert.equal(qianfanModels.find((model) => model.id === "ernie-4.5-turbo-128k")?.maxOutputTokens, 12_288);
	assert.equal(qianfanModels.find((model) => model.id === "ernie-4.5-turbo-vl")?.capabilities.imageInput, true);
	assert.equal(qianfanModels.find((model) => model.id === "ernie-4.5-turbo-vl-32k")?.contextWindowTokens, 32_768);
	const openaiModels = getProviderFallbackModels("openai");
	assert.equal(openaiModels.find((model) => model.id === "gpt-5.6-sol")?.contextWindowTokens, 1_050_000);
	assert.equal(openaiModels.find((model) => model.id === "gpt-5.6-sol")?.maxOutputTokens, 128_000);
	assert.equal(openaiModels.find((model) => model.id === "gpt-5.6-sol")?.capabilities.webSearch, true);
	assert.equal(openaiModels.find((model) => model.id === "gpt-5.6-sol")?.capabilities.vision, true);
	assert.equal(openaiModels.find((model) => model.id === "gpt-5.6-terra")?.capabilities.reasoning, true);
	assert.equal(openaiModels.find((model) => model.id === "gpt-5.6-luna")?.capabilities.tools, true);
	assert.equal(openaiModels.find((model) => model.id === "gpt-5.3-codex")?.contextWindowTokens, 400_000);
	assert.equal(openaiModels.find((model) => model.id === "gpt-5.3-codex")?.capabilities.imageInput, true);
	assert.equal(openaiModels.find((model) => model.id === "gpt-5.3-codex")?.capabilities.tools, true);
	assert.equal(openaiModels.find((model) => model.id === "gpt-image-2")?.capabilities.imageGeneration, true);
	assert.equal(openaiModels.find((model) => model.id === "gpt-image-2")?.capabilities.imageEdit, undefined);
	assert.equal(getCatalogModels().length >= providerIds.length, true);
});

test("provider model list fallback returns normalized capabilities", async (): Promise<void> => {
	const result = await listProviderModels("openai", undefined, undefined);
	const model = result.models.find((item) => item.id === "gpt-5.6-sol");
	const zhipuResult = await listProviderModels("zhipu", undefined, undefined);
	const dashscopeResult = await listProviderModels("dashscope", undefined, undefined);
	const volcengineResult = await listProviderModels("volcengine", undefined, undefined);
	const minimaxResult = await listProviderModels("minimax", undefined, undefined);
	const stepfunResult = await listProviderModels("stepfun", undefined, undefined);
	const iflytekResult = await listProviderModels("iflytek", undefined, undefined);
	const opencodeResult = await listProviderModels("opencode", undefined, undefined);
	const opencodeGoResult = await listProviderModels("opencode_go", undefined, undefined);
	const qianfanResult = await listProviderModels("qianfan", undefined, undefined);

	assert.equal(result.source, "fallback");
	assert.equal(model?.capabilities.reasoning, true);
	assert.equal(model?.capabilities.tools, true);
	assert.equal(model?.capabilities.webSearch, true);
	assert.equal(model?.capabilities.vision, true);
	assert.equal(result.models.find((item) => item.id === "gpt-5.3-codex")?.capabilities.tools, true);
	assert.equal(result.models.find((item) => item.id === "gpt-image-2")?.capabilities.imageGeneration, true);
	assert.equal(zhipuResult.models.find((item) => item.id === "glm-image")?.capabilities.imageGeneration, true);
	assert.equal(zhipuResult.models.find((item) => item.id === "glm-5.2")?.capabilities.webSearch, true);
	assert.equal(zhipuResult.models.find((item) => item.id === "glm-image")?.capabilities.imageEdit, undefined);
	assert.equal(zhipuResult.models.find((item) => item.id === "cogview-4")?.capabilities.imageGeneration, true);
	assert.equal(zhipuResult.models.find((item) => item.id === "cogview-4")?.capabilities.imageEdit, undefined);
	assert.equal(dashscopeResult.models.find((item) => item.id === "qwen-image-2.0")?.capabilities.imageGeneration, true);
	assert.equal(dashscopeResult.models.find((item) => item.id === "qwen-image-2.0")?.capabilities.imageEdit, true);
	assert.equal(dashscopeResult.models.find((item) => item.id === "qwen-image")?.capabilities.imageGeneration, true);
	assert.equal(dashscopeResult.models.find((item) => item.id === "qwen-image")?.capabilities.imageEdit, undefined);
	assert.equal(dashscopeResult.models.find((item) => item.id === "qwen-image-edit")?.capabilities.imageGeneration, undefined);
	assert.equal(dashscopeResult.models.find((item) => item.id === "qwen-image-edit")?.capabilities.imageEdit, true);
	assert.equal(volcengineResult.models.find((item) => item.id === "doubao-seed-evolving")?.capabilities.vision, true);
	assert.equal(volcengineResult.models.find((item) => item.id === "doubao-seedream-5-0-pro-260628")?.capabilities.imageGeneration, true);
	assert.equal(minimaxResult.models.find((item) => item.id === "MiniMax-M3")?.capabilities.vision, true);
	assert.equal(minimaxResult.models.find((item) => item.id === "MiniMax-M3")?.capabilities.imageInput, true);
	assert.equal(minimaxResult.models.find((item) => item.id === "image-01")?.capabilities.imageGeneration, true);
	assert.equal(minimaxResult.models.find((item) => item.id === "image-01")?.capabilities.imageEdit, undefined);
	assert.equal(stepfunResult.models.find((item) => item.id === "step-3.7-flash")?.capabilities.vision, true);
	assert.equal(stepfunResult.models.find((item) => item.id === "step-3.7-flash")?.capabilities.imageInput, true);
	assert.equal(stepfunResult.models.find((item) => item.id === "step-3.7-flash")?.capabilities.reasoning, true);
	assert.equal(stepfunResult.models.find((item) => item.id === "step-3.7-flash")?.capabilities.tools, true);
	assert.equal(iflytekResult.models.find((item) => item.id === "4.0Ultra")?.capabilities.tools, true);
	assert.equal(iflytekResult.models.find((item) => item.id === "pro-128k")?.contextWindowTokens, 131_072);
	assert.equal(opencodeResult.models.find((item) => item.id === "kimi-k2.7-code")?.capabilities.tools, true);
	assert.equal(opencodeResult.models.find((item) => item.id === "deepseek-v4-pro")?.capabilities.reasoning, true);
	assert.equal(opencodeResult.models.find((item) => item.id === "minimax-m3")?.contextWindowTokens, 1_000_000);
	assert.equal(opencodeGoResult.models.find((item) => item.id === "kimi-k3")?.endpointType, "openai-chat-completions");
	assert.equal(opencodeGoResult.models.find((item) => item.id === "minimax-m3")?.endpointType, "anthropic-messages");
	assert.equal(opencodeGoResult.models.find((item) => item.id === "minimax-m3")?.capabilities.vision, true);
	assert.equal(opencodeGoResult.models.find((item) => item.id === "qwen3.6-plus")?.endpointType, "anthropic-messages");
	assert.equal(qianfanResult.models.find((item) => item.id === "ernie-5.1")?.capabilities.tools, true);
	assert.equal(qianfanResult.models.find((item) => item.id === "ernie-5.0")?.capabilities.vision, true);
	assert.equal(qianfanResult.models.find((item) => item.id === "ernie-x1.1")?.contextWindowTokens, 65_536);
});
