import type { ToolPolicy } from "./tool-policy.js";

export const TOOL_POLICIES: Record<string, ToolPolicy> = {
	"mcp_godot_get_project_summary": { risk: "read" },
	"mcp_godot_list_project_files": { risk: "read" },
	"mcp_godot_list_scenes": { risk: "read" },
	"mcp_godot_list_scripts": { risk: "read" },
	"mcp_godot_read_text_file": { risk: "read" },
	"mcp_godot_search_text": { risk: "read" },
	"mcp_godot_get_project_log_config": { risk: "read" },
	"mcp_godot_list_project_logs": { risk: "read" },
	"mcp_godot_read_project_log": { risk: "read" },
	"mcp_godot_get_project_settings": { risk: "read" },
	"mcp_godot_get_editor_config_summary": { risk: "read" },
	"mcp_godot_get_editor_settings": { risk: "read" },
	"mcp_godot_list_editor_config_files": { risk: "read" },
	"mcp_godot_read_editor_config_file": { risk: "read" },
	"mcp_godot_get_editor_project_state": { risk: "read" },
	"mcp_godot_get_recent_projects": { risk: "read" },
	"mcp_godot_propose_set_project_setting": { risk: "propose" },
	"mcp_godot_set_project_setting": { risk: "write" },
	"mcp_godot_propose_unset_project_setting": { risk: "propose" },
	"mcp_godot_unset_project_setting": { risk: "write" },
	"mcp_godot_propose_create_text_file": { risk: "propose" },
	"mcp_godot_create_text_file": { risk: "write" },
	"mcp_godot_propose_overwrite_text_file": { risk: "propose" },
	"mcp_godot_overwrite_text_file": { risk: "write" },
	"mcp_godot_propose_replace_text_in_file": { risk: "propose" },
	"mcp_godot_replace_text_in_file": { risk: "write" },
	"mcp_godot_delete_file": { risk: "destructive" },
	"mcp_godot_inspect_scene_tree": { risk: "read" },
	"mcp_godot_propose_create_scene": { risk: "propose" },
	"mcp_godot_create_scene": { risk: "write" },
	"mcp_godot_propose_add_node_to_scene": { risk: "propose" },
	"mcp_godot_add_node_to_scene": { risk: "write" },
	"mcp_godot_propose_attach_script_to_node": { risk: "propose" },
	"mcp_godot_attach_script_to_node": { risk: "write" },
	"mcp_godot_propose_connect_signal_in_scene": { risk: "propose" },
	"mcp_godot_connect_signal_in_scene": { risk: "write" },
	"mcp_godot_propose_apply_scene_patch": { risk: "propose" },
	"mcp_godot_apply_scene_patch": { risk: "write" },
	"mcp_godot_editor_get_context": { risk: "read" },
	"mcp_godot_editor_get_selected_nodes": { risk: "read" },
	"mcp_godot_editor_inspect_node": { risk: "read" },
	"mcp_godot_editor_apply_scene_patch": { risk: "write" },
	"mcp_godot_lsp_get_status": { risk: "read" },
	"mcp_godot_lsp_get_file_diagnostics": { risk: "read" },
	"mcp_godot_lsp_get_document_symbols": { risk: "read" },
	"mcp_godot_lsp_hover": { risk: "read" },
	"mcp_godot_lsp_goto_definition": { risk: "read" },
	"mcp_godot_dap_get_status": { risk: "read" },
	"mcp_godot_dap_get_last_error": { risk: "read" },
	"mcp_godot_dap_get_stack_trace": { risk: "read" },
	"mcp_godot_dap_get_variables": { risk: "read" },
	"mcp_terminal_get_capabilities": { risk: "read" },
	"mcp_terminal_run_safe_preset": { risk: "verify" },
	"mcp_terminal_run_write_preset": { risk: "write" },
	"mcp_terminal_run_godot_scene_script": { risk: "write" },
};

export const HARD_BLOCKED_TOOLS: Set<string> = new Set([]);
